"""outbox table

Revision ID: 1872edea254c
Revises: 772a0ecf9ec5
Create Date: 2023-01-23 10:46:00.450421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1872edea254c'
down_revision = '772a0ecf9ec5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_messages',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('aggregate_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('aggregate_type', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_on', sa.DateTime(), nullable=False),
    sa.Column('published_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbox_messages')
    # ### end Alembic commands ###
