"""create first tables(security migration)

Revision ID: 772a0ecf9ec5
Revises: 08bb38c0dc08
Create Date: 2023-01-19 16:25:16.301917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772a0ecf9ec5'
down_revision = '08bb38c0dc08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_access_subsidiary_company', sa.Column('company_phone', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_access_subsidiary_company', 'company_phone')
    # ### end Alembic commands ###
